// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include <frc/motorcontrol/Spark.h>
#include <frc2/command/SubsystemBase.h>
#include <frc/DoubleSolenoid.h>
#include <frc/Compressor.h>

class Grabber: public frc2::SubsystemBase {

private:
    frc::DoubleSolenoid m_grabberSolenoid{frc::PneumaticsModuleType::REVPH, 0, 1}; //TODO: Correct Module Type? && Tuned Values
    frc::Compressor m_compressor{frc::PneumaticsModuleType::REVPH};

public:
    Grabber();

    void Periodic() override;
    void SimulationPeriodic() override;
    void GrabberOpen();
    void GrabberClose();
    void CompressorEnable();
    void CompressorDisable();
    void GrabberStop();
};