// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

#include "commands/ArmForwardCommand.h"

ArmForwardCommand::ArmForwardCommand(Arm* m_arm)
:m_arm(m_arm){

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("ArmForwardCommand");
    AddRequirements(m_arm);
}

// Called just before this Command runs the first time
void ArmForwardCommand::Initialize() {
   m_arm->ArmForward();
}

// Called repeatedly when this Command is scheduled to run
void ArmForwardCommand::Execute() {
}

// Make this return true when this Command no longer needs to run execute()
bool ArmForwardCommand::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void ArmForwardCommand::End(bool interrupted) {
    m_arm->ArmStop();
}

bool ArmForwardCommand::RunsWhenDisabled() const {
    return false;
}