// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "subsystems/Arm.h"

#include <frc/smartdashboard/SmartDashboard.h>
#include <wpi/raw_ostream.h> // for wpi outs()


Arm::Arm(){
    SetName("Arm");
    SetSubsystem("Arm");

    AddChild("ArmMotor", &m_armMotor);
    
	m_armMotor.SetInverted(false);
}

void Arm::Periodic() {
    // Put code here to be run every loop
    frc::SmartDashboard::PutNumber("Arm Angle : ", m_potentiometer);
}

void Arm::SimulationPeriodic() {
}

// Put methods for controlling this subsystem here and call from commands

void Arm::ArmExtend(){ 
    // Extend Arm 

    //extend code here
}

void Arm::ArmRetract(){ 
    // Retract Arm 

    //retract code here
}

void Arm::ArmForward(){ 
    // Lower Arm 
    if (frontLimitSwitch.Get())
    {
        this->ArmStop();
    }
    else { 
        m_armMotor.Set(-0.35); 
    } 
}

void Arm::ArmBackward(){
    // Raise Arm
    if(backLimitSwitch.Get())
    {
        this->ArmStop();
    }
    else{
    m_armMotor.Set(0.35);
}
}

void Arm::ArmStop(){
    // stop the arm
    m_armMotor.Set(0.0);
}