// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "subsystems/Arm.h"

#include <frc/smartdashboard/SmartDashboard.h>
#include <wpi/raw_ostream.h> // for wpi outs()


Arm::Arm(){
    SetName("Arm");
    SetSubsystem("Arm");

    AddChild("ArmPivotMotor1", &m_armPivotMotor1);
    AddChild("ArmPivotMotor2", &m_armPivotMotor2);
    AddChild("ArmExtendMotor", &m_armExtendMotor);
    AddChild("m_armPivotMotors", &m_armPivotMotors);
    
    m_armPivotMotor2.SetInverted(true);
    m_armPivotMotor1.SetInverted(false);
    m_armExtendMotor.SetInverted(false);
}

void Arm::Periodic() {
    // Put code here to be run every loop
    //frc::SmartDashboard::PutNumber("Arm Angle : ", m_potentiometer);
}

void Arm::SimulationPeriodic() {
}

// Put methods for controlling this subsystem here and call from commands

void Arm::ArmExtend(){ 
    // Extend Arm 
        m_armExtendMotor.Set(0.25); 
}

void Arm::ArmRetract(){ 
    // Retract Arm 
        m_armExtendMotor.Set(-0.25); 
}

void Arm::ArmForward(){ 
    // Raise Arm
    m_armPivotMotors.Set(-0.5);
}

void Arm::ArmBackward(){
    // Lower Arm
    m_armPivotMotors.Set(0.5);
}

void Arm::ArmPivotStop(){
    // stop the arm
    m_armPivotMotors.Set(0.0);
}

void Arm::ArmExtendStop(){
    // stop the arm
    m_armExtendMotor.Set(0.0);
}