// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "subsystems/Claw.h"

#include <frc/smartdashboard/SmartDashboard.h>
#include <wpi/raw_ostream.h> // for wpi outs()


Claw::Claw(){
    SetName("Claw");
    SetSubsystem("Claw");

    AddChild("ClawMotor", &m_clawMotor);

    m_clawMotor.SetInverted(false);
}

void Claw::Periodic() {
    // Put code here to be run every loop
}

void Claw::SimulationPeriodic() {
}

// Put methods for controlling this subsystem here and call from commands

void Claw::ClawOpen(){
    //Open the Claw
}

void Claw::ClawClose(){
    //Close the Claw
}

void Claw::ClawStop(){
    // Stop the Claw
    m_clawMotor.Set(0.0); 
}